### ISSUE TITLE
Light logos for Canal Digitaal and TV Vlaanderen

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#260] opened 2018-01-07 16:19 UTC
The current logos 'canaldigitaal` and `tvvlaanderen` are hardly visible on a dark background.

First question is, is is a good idea to make a `light` variant?

And if so, should the letters be in opposite color (looks a bit yellow):
[M7logos_v1.zip](https://github.com/picons/picons-source/files/1609944/M7logos_v1.zip)

Or letters in white?
[M7logos_v2.zip](https://github.com/picons/picons-source/files/1609946/M7logos_v2.zip)

I'd opt for the white letters.

**Comment by AbuBaniaz** [comment] 2018-01-07 21:24
>First question is, is is a good idea to make a light variant?

If the logos are not visible, then the light versions will be beneficial.
We have svg versions of the files, so best to stick to use them instead of .png

**Comment by mcfly822** [comment] 2018-01-07 22:24
I also prefer the white version. I made them in svg.
The white is not the full white (ffffff), it has 2.5% grey (f9f9f9). I like this better, because it is better (even visible) in full white background, but not worse with black background.
If you don't like this, I can edit to full white.

[cd&tvv_light_mcfly822.zip](https://github.com/picons/picons-source/files/1610249/cd.tvv_light_mcfly822.zip)

**Comment by mcfly822** [comment] 2018-01-07 22:36
Other M7 group company, Skylink has also this kind of logo:
![skylinkfw-163x55](https://user-images.githubusercontent.com/22531870/34654938-f634b6e8-f402-11e7-8409-f58aefc2ed32.png)

Sholdn't we change the existing (old) Skylink logo?

And another M7 company, Télésat has also this kind of logo, I made the light variant for this.
[telesat.light.zip](https://github.com/picons/picons-source/files/1610259/telesat.light.zip)

**Comment by Lexzie** [comment] 2018-01-08 00:47
@mcfly822 could you also make this logo?
![afbeelding](https://user-images.githubusercontent.com/14023349/34656042-f505a212-f413-11e7-9ced-0e69618963bd.png)
The square logo can remain red, just add the text `OCHUTNÁVKA` (notice the line above the `a`).

The indexes for this logo are:

**snp.index**
```
skylinkochutnavka=skylinkochutnavka
```

**Delete in srp.index**
```
1F4B_CA1_3_EB0000=skylink
```

**Add in srp.index**
```
1F4B_CA1_3_EB0000=skylinkochutnavka
```

`donkey monkey got issued`

**Comment by mcfly822** [comment] 2018-01-08 08:08
@Lexzie sorry, it is over my skills. The problem is, that I don't find a good resolution bitmap image, which I could draw in inkscape. And the font is not common, so I cannot write "OCHUTNÁVKA" as text, it must be drawed line by line. And this is impossible from a very low resolution image.

If I (or you) find a better resolution jpg or png, I can make the svg.

**Comment by Lexzie** [comment] 2018-01-08 12:37
Great!
I have searched a lot, but apparently (still) not in the best way.
Where and how did you find the svg??

**Comment by mcfly822** [comment] 2018-01-08 12:43
https://www.skylink.cz/novinky/80cs-joj-cinema-hd-na-predvolbe-skylink-ochutnavka
Here, at the first row under the title, there is a link to a pdf:
Přehled všech programových novinek za posledních 12 měsíců zde.
https://www.skylink.cz/doc/cms_library/noveprogramyvnabidce_cz-225.pdf

And in this pdf, the logo is in vector format 😉

**Comment by Lexzie** [comment] 2018-01-08 13:03
That's where I found the crappy logo, but extracting logo's from pdf is something I don't know how to do (yet).

**Comment by mcfly822** [comment] 2018-01-08 13:30
It's very simple: just open the pdf in inkscape. Iimport dialog will appear, choose Poppler/Cairo import, and you can select which page of the pdf you want to import (only one page/import). Then, if there is a vector graphic in the pdf, you can copy and edit it.

But before the import, you can easily decide whether the pdf contains vector or pixel graphic: if you open the pdf in any software, and zoom in. If the image quality remains good, it is in vector format, but if  getting worse, it is embedded pixel image.

**Comment by mcfly822** [comment] 2018-01-09 07:42
PR #263 merged.
@Lexzie If everything is okay, you can close this issue.

**Comment by mcfly822** [comment] 2018-01-11 10:55
@Lexzie is there anything else to do for this issue?

**Closed** 2018-01-11 12:10 UTC

**Comment by Lexzie** [comment] 2018-01-12 00:49
All three logos are fine, thanks!
