### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by daviok** [picons/picons-source#189] opened 2017-11-16 08:24 UTC
please accept those logos and links:
[logos.zip](https://github.com/picons/picons-source/files/1477798/logos.zip)

Sources:
https://upload.wikimedia.org/wikipedia/fr/e/e5/Logo_de_POLAR%2B.jpeg
http://i2.cdn.turner.com/cnn/2017/images/01/19/cnnmoneyswitz1_-_press_room.jpg
https://clefs.tv/images/BoosterlogoTransBig.png
https://upload.wikimedia.org/wikipedia/fr/e/e5/Espace2.svg
https://upload.wikimedia.org/wikipedia/fr/2/23/La1ere.svg
http://www.mediaone.ch/wp-content/uploads/2016/06/Logo_RadioLac_547x250.png
https://upload.wikimedia.org/wikipedia/commons/8/8b/Ajustement_Logo_2017.jpg
https://upload.wikimedia.org/wikipedia/fr/f/f7/Logo-lfm.jpg
https://images.radiovolna.net/_files/uploads/posts/2015-11/thumbs/1447158015_11174226_820195281397915_641298075630752624_o.jpg-851315.png
https://upload.wikimedia.org/wikipedia/commons/7/74/Logo_toxic_rocks_schwarz.png
https://www.digris.ch/wp/wp-content/uploads/2014/08/31_traxx.png
https://upload.wikimedia.org/wikipedia/fr/9/93/Logo-GRRIF.png
https://upload.wikimedia.org/wikipedia/commons/4/44/Logo_radio_RJB.jpg
https://upload.wikimedia.org/wikipedia/commons/b/b7/RTN_screen.jpg
https://upload.wikimedia.org/wikipedia/commons/9/9f/RFJ_screen.jpg

Add to snp-index

```
polarplus=polarplus
cnnmoneyswitzerland=cnnmoneyswitzerland
boostertv=boostertv
rtsespace2=rtsespace2
rts1lapremiere=rts1lapremiere
radiolac=radiolac
rougefm=rougefm
lausannefm=lausannefm
globalfm=globalfm
toxicfm=toxicfm
traxxfm=traxxfm
grrif=grrif
rjbbnj=rjbbnj
rtnbnj=rtnbnj
rfjbnj=rfjbnj

```

Add to srp-index:

```
240C_AC_1_FFFF0000=polarplus
24AA_4E_1_FFFF0000=cnnmoneyswitzerland
255E_A2_1_FFFF0000=boostertv
6A5_39_1_FFFF0000=rtsespace2
6A4_39_1_FFFF0000=rtslapremiere
6DE_48_1_FFFF0000=radiolac
6E2_48_1_FFFF0000=rougefm
6EF_34_1_FFFF0000=globalfm
6E4_48_1_FFFF0000=lausannefm
558_37_1_FFFF0000=toxicfm
59A_37_1_FFFF0000=traxxfm
6E6_48_1_FFFF0000=grrif
6D8_48_1_FFFF0000=rjbbnj
6D6_48_1_FFFF0000=rtnbnj
6D4_48_1_FFFF0000=rfjbnj







```

`donkey monkey got issued`

**Comment by mocram** [comment] 2017-11-16 18:12
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by daviok** [comment] 2017-11-16 20:22
hello , yes i read it , what is not working?

**Comment by mocram** [comment] 2017-11-16 20:57
Incorrectly named logos and the majority is of bad quality.

**Comment by daviok** [comment] 2017-11-16 21:01
ok got it for the named logos but those logos are the best i can find.
Do we need to convert to svg and zip them , do you know any good converter for jpg-png to svg ?
thanks mocram

**Comment by mocram** [comment] 2017-11-16 21:03
Servicerefs are also incorrect. Logos should be of good quality with transparency.

**Comment by mcfly822** [comment] 2017-11-16 21:06
I can improve the bad quality logos.

**Comment by daviok** [comment] 2017-11-16 21:08
`Only the part 296_5_85_C00000 is used, the parts 1_0_1_ and _0_0_0 must be removed.`
if it is :1:0:2:6C7:33:1:FFFF0000:0:0:0 serviceref is `2_6C7_33_1_FFFF0000` correct?

**Comment by mocram** [comment] 2017-11-16 21:11
No

**Comment by daviok** [comment] 2017-11-16 21:34
ok updated the service ref for the 3 first channels , should be ok for the others too now , for the logos i give the .zip and the png if mcfly822 wants to improve, please let me know

**Comment by mcfly822** [comment] 2017-11-17 14:11
I started to work on it, until now I drawed 4 logos in vector format. This takes a lot of time, and there is also a job and family, so I need some days to do this.

**Comment by daviok** [comment] 2017-11-17 15:38
thanks mcfly822 , no hurry for that :-)

**Comment by mcfly822** [comment] 2017-11-18 00:30
The RTL logo is already in the repo:
https://github.com/picons/picons-source/blob/master/build-source/logos/rtl-frakuherow.default.svg

**Comment by daviok** [comment] 2017-11-18 22:59
Macfly822 you are right, I though so because it is well know, sorry for that.

**Comment by mcfly822** [comment] 2017-11-19 09:02
No problem :-) 
Still working on the logos, I'll finish soon.

**Comment by mcfly822** [comment] 2017-11-20 09:34
I finished the work. I drawed almost every logos in inkscape, only globalfm is what I cannot make, because of the complicated color gradients. So I made it in GIMP, but low resolution. If it is not acceptable, maybe someone else can do it. If not, just ignore that logo.
Please @charlesduco or @mocram check the logos. (I did it with rsvg-convert, passed.)
[issue189_mcfly822_20171120.zip](https://github.com/picons/picons-source/files/1487077/issue189_mcfly822_20171120.zip)

**Comment by daviok** [comment] 2017-11-20 12:47
Nice thanks for the job done mcfly822 👍

**Comment by Lexzie** [comment] 2017-11-21 00:23
If we're already busy adding Swiss stations, Could anyone please also update these logos and add these links?
(For satellite, Hotbird 13°E)
[RTS_Lexzie.zip](https://github.com/picons/picons-source/files/1489522/RTS_Lexzie.zip)

Sources:
RTS Couleur 3: https://upload.wikimedia.org/wikipedia/fr/6/6e/Couleur3.svg
RTS Option musique: https://upload.wikimedia.org/wikipedia/fr/6/6c/OptionMusique.svg

**Add to snp-index**
```
srf1=radiosrf1
srf2kultur=srf2kultur
srf3=radiosrf3
srf4news=radiosrf4news
srfvirus=radiosrfvirus
srfmusikwelle=radiosrfmusikwelle
rts1ere=rts1lapremiere
espace2=rtsespace2
couleur3=rtscouleur3
optionmusique=rtsoptionmusique
reteuno=rsireteuno
retedue=rsiretedue
retetre=rsiretetre
swissclassic=radioswissclassic
swisspop=radioswisspop
swissjazz=radioswissjazz
swissclassique=radioswissclassic
srf1agso=radiosrf1
srf1bs=radiosrf1
srf1befrvs=radiosrf1
srf1lu=radiosrf1
srf1sg=radiosrf1
srf1zhsh=radiosrf1
srf1gr=radiosrf1
swissclassica=radioswissclassic
test14054=srfinfohd
```

**Add to srp-index**
```
36C5_6A4_13E_820000=radiosrf1
36C6_6A4_13E_820000=srf2kultur
36C7_6A4_13E_820000=radiosrf3
36D5_6A4_13E_820000=radiosrf4news
36C8_6A4_13E_820000=radiosrfvirus
36C9_6A4_13E_820000=radiosrfmusikwelle
36CA_6A4_13E_820000=radiorumantsch
36CB_6A4_13E_820000=rts1lapremiere
36CC_6A4_13E_820000=rtsespace2
36CD_6A4_13E_820000=rtscouleur3
36CE_6A4_13E_820000=rtsoptionmusique
36CF_6A4_13E_820000=rsireteuno
36D0_6A4_13E_820000=rsiretedue
36D1_6A4_13E_820000=rsiretetre
36D2_6A4_13E_820000=radioswissclassic
36D3_6A4_13E_820000=radioswisspop
36D4_6A4_13E_820000=radioswissjazz
36D7_6A4_13E_820000=radioswissclassic
36D8_6A4_13E_820000=radiosrf1
36D9_6A4_13E_820000=radiosrf1
36DA_6A4_13E_820000=radiosrf1
36DB_6A4_13E_820000=radiosrf1
36DC_6A4_13E_820000=radiosrf1
36DD_6A4_13E_820000=radiosrf1
36DE_6A4_13E_820000=radiosrf1
36DF_6A4_13E_820000=radioswissclassic
36E6_6A4_13E_820000=srfinfohd
```

**Delete from srp-index:**
```
385_2134_13E_820000=srf1
38B_2134_13E_820000=srfzwei
38F_2134_13E_820000=srfinfo
39A_2134_13E_820000=srf2kultur
3C1_2134_13E_820000=srfinfohd
36B3_6A4_13E_820000=rsila1
36B9_6A4_13E_820000=rsila2
```
`donkey monkey got issued'

**Comment by daviok** [comment] 2017-11-23 09:23
Is it possible to add a new missing logo here , or do i need to open a new issue thread?

**Comment by AbuBaniaz** [comment] 2017-11-23 09:27
New issue please

**Comment by daviok** [comment] 2017-11-23 10:08
ok done thanks AbuBaniaz , the auto build server is off  or ?

**Comment by AbuBaniaz** [comment] 2017-11-23 23:23
Is everything done? If so, please  close the issue.

**Comment by Lexzie** [comment] 2017-11-24 01:53
I miss the snp-links additions

**Comment by daviok** [comment] 2017-11-24 07:31
do the thread need to be closed for the picons to be present in the next .ipk.
because all the radios and channels are not present in the 2017-11-23--17-46-24_all.ipk

**Comment by mocram** [comment] 2017-11-24 07:35
If it's in git with a commit, it can be closed.

**Comment by daviok** [comment] 2017-11-24 07:38
thanks @mocram 
because i can see all the new swiss logo in picons-source/build-source/logos/
but only teleclubzoom.png is present after installing the .ipk.
I need to wait the next ipk build ?

**Comment by mocram** [comment] 2017-11-24 07:44
Last build is from `2017-11-23--17-46-24`, the swiss commit by Abu was made only 5 hours ago. The build starts at 0:00 anything commited afterwards won't end up in a build.

**Comment by daviok** [comment] 2017-11-24 07:48
ah right 
I will wait the next build , that's what i though.

**Comment by mocram** [comment] 2017-11-24 07:53
The build version date, is not the date that the build started, but the actual date and time of the last commit that is included. I thought about perhaps just using the commit hash, but that on its own is quite useless when browsing the downloads to see if an update is available.

**Comment by Lexzie** [comment] 2017-11-24 19:38
I'm sorry but a lot of the links mentioned in this topic are not present in snp- or srp-index.

**Please add to snp-index**
```
boostertv=boostertv
cnnmoneyswitzerland=cnnmoneyswitzerland
globalfm=globalfm
grrif=grrif
lausannefm=lausannefm
polarplus=polarplus
rtsespace2=rtsespace2
rts1lapremiere=rtslapremiere
radiolac=radiolac
36C5_6A4_13E_820000=radiosrf1
srf1agso=radiosrf1
srf1bs=radiosrf1
srf1befrvs=radiosrf1
srf1lu=radiosrf1
srf1sg=radiosrf1
srf1zhsh=radiosrf1
srf1gr=radiosrf1
srf3=radiosrf3
srf4news=radiosrf4news
srfmusikwelle=radiosrfmusikwelle
swissclassic=radioswissclassic
swisspop=radioswisspop
swissjazz=radioswissjazz
swissclassica=radioswissclassic
swissclassique=radioswissclassic
rfjbnj=rfjbnj
rjbbnj=rjbbnj
rougefm=rougefm
reteuno=rsireteuno
retedue=rsiretedue
retetre=rsiretetre
rtnbnj=rtnbnj
rts1ere=rts1lapremiere
espace2=rtsespace2
couleur3=rtscouleur3
optionmusique=rtsoptionmusique
test14054=srfinfohd
srf2kultur=srf2kultur
toxicfm=toxicfm
traxxfm=traxxfm
```

**Please add to srp-index**
```
255E_A2_1_FFFF0000=boostertv
24AA_4E_1_FFFF0000=cnnmoneyswitzerland
6EF_34_1_FFFF0000=globalfm
6E6_48_1_FFFF0000=grrif
6E4_48_1_FFFF0000=lausannefm
240C_AC_1_FFFF0000=polarplus
6DE_48_1_FFFF0000=radiolac
6D4_48_1_FFFF0000=rfjbnj
6D8_48_1_FFFF0000=rjbbnj
6E2_48_1_FFFF0000=rougefm
6D6_48_1_FFFF0000=rtnbnj
6A5_39_1_FFFF0000=rtsespace2
6A4_39_1_FFFF0000=rtslapremiere
558_37_1_FFFF0000=toxicfm
59A_37_1_FFFF0000=traxxfm
```
**Please delete from srp-index (double entry)**
```
36D7_6A4_13E_820000=suisseclassique
```
`donkey monkey got issued`

**Comment by daviok** [comment] 2017-11-26 13:01
it still missing some entries on the 25-11 update

6D4_48_1_FFFF0000=rfjbnj
6D6_48_1_FFFF0000=rtnbnj
255E_A2_1_FFFF0000=boostertv
24AA_4E_1_FFFF0000=cnnmoneyswitzerland
6DE_48_1_FFFF0000=radiolac

do i need to wait the 26 or later updates ?

**Comment by mocram** [comment] 2017-11-26 13:35
This happens when the issue is not correct from the start.

**Comment by mocram** [comment] 2017-11-26 13:35
https://github.com/picons/picons-source/commit/013ee14fb4b07e6efa26190f17c95cff05f32d1e

**Closed by mocram** 2017-11-26 13:35 UTC

**Comment by daviok** [comment] 2017-11-26 15:46
ok thanks @mocram
