### ISSUE TITLE
Some logos don't build correctly.

### ISSUE THREAD

**Issue by TheLegoBatman** [picons/picons-source#430] opened 2018-06-01 17:51 UTC
Some logos aren't building correctly. They have the wrong channel name. When building the service list they look like this:
```
1_0_1_1_1_1_1EAD9C_0_0_0        |  IRAN TODAY   |  1_1_1_1EAD9C=nessma
1_0_16_1_1_1_CE4AAAA_0_0_0      |  BOM          |  1_1_1_CE4AAAA=antena1
```

They point to the wrong channel name.  When building the logos using srp they build the wrong logo. When building the logos using srp-full the script makes the logo ```1_0_1_1_1_1_CE4AAAA_0_0_0.png``` for Bom. Even though openvix reads the other logos that the script adds 1_0_1 to the beginning of the logo name, it doesn't display this one. Example:
```
1_0_16_101D_451_35_C00000_0_0_0    |  AXN Deutschland   |  101D_451_35_C00000=axn
```
ends up being built as ```1_0_1_101D_451_35_C00000_0_0_0.png``` but openvix still displays it.
I am not sure if I explained this in the best way. Please ask for more info if needed.
Thanks

**Comment by mocram** [comment] 2018-06-01 18:09
So your receiver shows a different name then BOM for 1_0_16_1_1_1_CE4AAAA_0_0_0 ?

I'm confused about the actual problem

**Comment by TheLegoBatman** [comment] 2018-06-01 18:12
The channel BOM is built as 1_0_1_1_1_1_CE4AAAA_0_0_0.png instead of 1_0_16_1_1_1_CE4AAAA_0_0_0.png . Doesn't get displayed.

**Comment by mocram** [comment] 2018-06-01 18:13
srp-full always builds using 1_0_1, because it doesn't know it should be 1_0_16

**Comment by TheLegoBatman** [comment] 2018-06-01 18:15
If building using the service list it builds it as antena1 logo. Is there a way to change this instead of doing it manually every time?

**Comment by TheLegoBatman** [comment] 2018-06-01 19:50
It's not the list. The one downloaded from picons.eu is the same.

**Comment by mocram** [comment] 2018-06-01 20:33
files from picons.eu do not use a servicelist to build, it just takes what's in srp.index

**Comment by TheLegoBatman** [comment] 2018-06-01 20:40
It builds with the 1_0_1 at the beginning so I guess there is no way to change that for the full build. That channel logo doesn't show up on vix from the picons downloaded from picons.eu. I will just keep doing it manually for now.

**Comment by AbuBaniaz** [comment] 2018-06-01 20:42
The picon file in OpenVixand OpenPLi has this
`
https://github.com/OpenViX/enigma2/blob/master/lib/python/Components/Renderer/Picon.py#L75:L101
`

```
def getPiconName(serviceName):
	#remove the path and name fields, and replace ':' by '_'
	fields = GetWithAlternative(serviceName).split(':', 10)[:10]
	if not fields or len(fields) < 10:
		return ""
	pngname = findPicon('_'.join(fields))
	if not pngname and not fields[6].endswith("0000"):
		#remove "sub-network" from namespace
		fields[6] = fields[6][:-4] + "0000"
		pngname = findPicon('_'.join(fields))
	if not pngname and fields[0] != '1':
		#fallback to 1 for other reftypes
		fields[0] = '1'
		pngname = findPicon('_'.join(fields))
	if not pngname and fields[2] != '1':
		#fallback to 1 for services with different service types
		fields[2] = '1'
		pngname = findPicon('_'.join(fields))
	if not pngname: # picon by channel name
		name = ServiceReference(serviceName).getServiceName()
		name = unicodedata.normalize('NFKD', unicode(name, 'utf_8', errors='ignore')).encode('ASCII', 'ignore')
		name = re.sub('[^a-z0-9]', '', name.replace('&', 'and').replace('+', 'plus').replace('*', 'star').lower())
		if len(name) > 0:
			pngname = findPicon(name)
			if not pngname and len(name) > 2 and name.endswith('hd'):
				pngname = findPicon(name[:-2])
return pngname
```
It should show. It was changed in April 2017.

Which image build and which receiver please?

**Comment by mocram** [comment] 2018-06-01 20:43
I think I finally found what you meant with bom and iran today.....

But what do you mean with "manually"?

**Comment by TheLegoBatman** [comment] 2018-06-01 20:45
Vuplus duo2 with Openvix 5.1.026. Same happened before I updated to this version. 
@mocram I meant changing the logo frequency manually for that channel. I probably didn't explain things too well :)

**Comment by AbuBaniaz** [comment] 2018-06-01 20:48
Is this the OSD picon or the one on the LCD?

**Comment by mocram** [comment] 2018-06-01 20:49
Let me recap, bom has the almost exact same serviceref as antena1, `1_1_1_CE4......`, last digits differ, yeat he picks the wrong link....
Iran Today should not get linked according to srp.index.


Correct?

**Comment by mocram** [comment] 2018-06-01 20:56
I know why this is happening, I put this in the script on purpose, because in the past people had slightly different results for the last few digits... how certain are we that antena1 still exists?

**Comment by TheLegoBatman** [comment] 2018-06-01 20:57
@AbuBaniaz It shows on the LCD but not on the OSD.
@mocram I built the service list to test and yes it did indeed show as above. I usually build the service list to make sure the frequencies we are given are correct before updating the srp index. Apart from that  I always build the full picons. The BOM picon just doesn't show. The Iran Today just came up like that when I checked the service list.

**Comment by TheLegoBatman** [comment] 2018-06-01 20:57
Antena 1 exists. 100% sure

**Comment by AbuBaniaz** [comment] 2018-06-01 20:59
We changed the picon code in openvix because the radio picons in this project did not show. Previously, if not `2`, they were changed to `1`. After the change, if not `1`, it was changed to `1`.

I'm not sure if the LCD4Liniux plugin which drives the picon code for the duo2 has been adapted. But this just throws that theory out
>It shows on the LCD but not on the OSD.

**Comment by TheLegoBatman** [comment] 2018-06-01 21:32
They are both in Hispasat. Bom is a tv logo and antena1 is a radio logo. They both exist at the moment.

**Comment by mocram** [comment] 2018-06-01 21:34
OK, then We'll just have to build more strict and include the last 4 digits when doing the lookup....

Is this issue solved if I adjust the script?

**Comment by TheLegoBatman** [comment] 2018-06-01 21:38
I think it will.

**Comment by mocram** [comment] 2018-06-01 21:50
Ok give it a go....

Not sure how the application VDR is handling those two stations, because VDR has by default only the first 3 numbers CE4, the rest gets filled in with 0000. Aarghh it's been so long I did all of this mess. I even had some conversations with the inventor of the serviceref in the past and I already told him that for picon use he really screwed things up. :-)

**Comment by mocram** [comment] 2018-06-01 21:55
Be warned, this can result in other channels now missing a logo.

**Comment by TheLegoBatman** [comment] 2018-06-01 21:57
Probably easier to just remove that antena1 ref from the srp index and leave things as they are.

**Comment by mocram** [comment] 2018-06-01 22:00
But what if it actually has to be:

```
1_0_2_1_1_1_CE4B0E7=antena1
1_0_16_1_1_1_CE4B0E7=bom
```

The last 4 digits deviating perhaps by a badly aligned sat dish? If the above sample is the correct answer, we have a problem. @AbuBaniaz Thoughts?

**Comment by Lexzie** [comment] 2018-06-01 22:06
CE4 stands for 30,0W.
For western satellites it is calculated like this:
3600-(orbital position)*10 and then convert the outcome to hexadecimal.
In case of 30,0W: 3600-(30,0)*10=3300 => CE4 in hexadecimal.

In most cases this is followed by four zero's in the namespace.
But, for reasons I don't know, sometimes it is not.
If that is the case somehow the four digits represent the frequency that is scanned.
The problem with that is if you scan f.e. 12476 H you get a different namespace then when scanning f.e. 12475 H, while you have the same station.
I guess that's the reason why the last four digits were ignored.

The same problem occurs when assigning EPG to the service reference. The rule (at least for xmltv-EPG from Rytec) is you must scan **exactly** the frequency that is listed on [Lyngsat](www.lyngsat.com). The satellites.xml (at least on OpenPLi) is also based on the data on Lyngsat.

If you ignore the last four digits it can also cause a problem because some operators don't see the need to use a unique combination of SID/NID/TID on different frequencies on the same satellite.

I have however for Antena 1 the following servicereferences:
`1_0_2_FA_66_53_CE40000_0_0_0` and `1_0_2_520_30_36_CE40000_0_0_0`
So, no `1_0_2_1_1_1_CE4B0E7`. On what frequency you get that?

I guess by deleting `1_1_1_CE4B0E7=antena1` from srp.index and adding
```
FA_66_53_CE40000=antena1
520_30_36_CE40000=antena1
```
to srp.index we have already solved this?

**Comment by Lexzie** [comment] 2018-06-01 22:10
By the way, Bom TV is listed on Hispasat on two frequencies as:
```
1_0_16_1_1_1_CE4AAAA_0_0_0
1_0_19_1_1_1_CE42CEF_0_0_0
```

**Comment by mocram** [comment] 2018-06-01 22:11
@Lexzie You are correct, kingofsat also lists them on a different frequency, so it's not possible.

I'm reverting the script adjustments

**Comment by TheLegoBatman** [comment] 2018-06-01 22:21
@Lexzie How can't I find the ```1_0_19_1_1_1_CE42CEF_0_0_0``` on KingofSat?

**Comment by mocram** [comment] 2018-06-01 22:23
@Lexzie Can we assume that something different than 0000 at the end could be a cause of bad scanning, misaligned dish, perhaps from blindscan? Perhaps we should keep our eyes op as to whom submits those numbers and ask how he/she got the channellist......

**Comment by mocram** [comment] 2018-06-01 22:29
@TheLegoBatman How exactly are you coming up with your channel list? Because this also looks like an out of whack namespace?

`1_0_1_1_1_1_1EAD9C_0_0_0        |  IRAN TODAY`

**Comment by TheLegoBatman** [comment] 2018-06-01 22:31
I downloaded this list yesterday from vhannibal for full motor updated on 30th May.

**Comment by mocram** [comment] 2018-06-01 22:39
Would have been a lot easier if they never invented picons. :-) Or at the very least dropped al of this hexadecimal bullshit and just hashed some user readable values.

If any one of you guys can come up with a 100% easy to use foolproof, 100% accurate way of linking picons besides serviceref or snp, let me know. Perhaps we are big enough to persuade some image builders...

**Comment by Lexzie** [comment] 2018-06-01 23:19
> @Lexzie How can't I find the 1_0_19_1_1_1_CE42CEF_0_0_0 on KingofSat?

Not, you'll have to scan the frequency and read out the service reference.
Bom TV should transmit on 10922 V and 11503 H, see https://www.lyngsat.com/tvchannels/es/Bom-TV.html

> @Lexzie Can we assume that something different than 0000 at the end could be a cause of bad scanning, misaligned dish, perhaps from blindscan? Perhaps we should keep our eyes op as to whom submits those numbers and ask how he/she got the channellist......

No, that's not the case. It must be caused by the satellite operator I think.
F.e. on BulgariaSat 1 at 1.9°E you'll have 12380 H and I can't get a namespace ending on four zero's, while on the same satellite on f.e. 12303 H it is no problem.
Scanning with 12380 gives `13305C`
Scanning with 12378 gives `13305A`
Scanning with 12377 gives `133059`
Scanning with 12377 gives `133058`

Scanning with 12381 gives `13305D`
Scanning with 12382 gives `13305E`

The dish is perfectly alligned, by the way if you missallign the dish a bit, but still enough signal, you'll still get the same results.

The only way to deal with this (when you want to use the last four digits) is to exactly scan the frequency that is listed on Lyngsat because that's also the source for the satellites.xml


> @TheLegoBatman How exactly are you coming up with your channel list? Because this also looks like an out of whack namespace?
> 
> `1_0_1_1_1_1_1EAD9C_0_0_0 | IRAN TODAY`

That namespace is also okay, it's more common that you think. Especially on satellites/frequencies not ment for DTH reception.

Just check out these stations on Eutelsat 3B:
```
AL-rassd		1_0_1_1_1_FFFF_1EACC3_0_0_0
ALNAEEM TV		1_0_1_1_1_FFFF_1EB103_0_0_0
BAYYNAT-TV		1_0_1_1_1_FFFF_1EAD97_0_0_0
ERICSSON		1_0_1_1_1_FFFF_1E30D9_0_0_0
ERICSSON		1_0_1_1_1_FFFF_1EADA2_0_0_0
Ettounisia		1_0_1_1_1_FFFF_1E30F3_0_0_0
Hispa ntv Service	1_0_1_1_1_FFFF_1EACE8_0_0_0
KARBALA TV		1_0_1_1_1_FFFF_1E30EA_0_0_0
LuaLua			1_0_1_1_1_FFFF_1EAD56_0_0_0
Pink DSNG		1_0_1_1_1_FFFF_1E31C1_0_0_0
Service-1		1_0_1_1_1_FFFF_1E2D7D_0_0_0
Service-1		1_0_1_1_1_FFFF_1EAD5A_0_0_0
Service-1		1_0_1_1_1_FFFF_1EAD9F_0_0_0
SYRIA NEWS		1_0_1_1_1_FFFF_1E2CD3_0_0_0
```

If you ignore the last four digits I don't know how to distinguish these references.

About `1_0_1_1_1_1_1EAD9C_0_0_0 | IRAN TODAY`
There is no logo for Iran today (yet).

The link `1_1_1_1EB120=nessma` is correct (with the last four digits) because Nessma is `1_0_1_1_1_1_1EB120_0_0_0`.


By the way: This mess with service references is one of the main reasons I switched to snp-picons.

**Comment by mocram** [comment] 2018-06-01 23:32
I've had enough for today, just close the issue if all is well or just ping me with the best way to go forward, ignore or include the last 3/4 digits......

**Comment by AbuBaniaz** [comment] 2018-06-02 01:46
Enigma2 ignores the extra details (sub network) in the namespace by **default**. You can enable it if you want on PLI/ViX.  This applies to other images who have who take/contribute code to/from them. Not sure if the guys have enabled this or left it at default. I'll need to scan later

However, for the purposes of this project, it should not matter if we are ignoring the **last** 4 digits of the namespace. This is because the picon code will work whether you have the namespace sub network enabled or not. 

scanning - sub network
```
https://github.com/OpenViX/enigma2/commit/082ab78e41cb71581a3043c7a49c97eb2bb86116
```

picon - sub network
```
https://github.com/OpenViX/enigma2/commit/67b3661ca11ce5b2a3c8e33339382b288b1a0261#diff-d15765b2bac22e8bfab70da2c42d37d5
```

PLI and OE-A images use the satteltes.xml file from Lyngsat. A few images use Kingofsat which has slightly different positions for some satellites. `0.8w` and `1w` is the most common bone of contention.

**Comment by Lexzie** [comment] 2018-06-02 07:16
I am away for the weekend, but I have some ideas. I need to work that out after the weekend.

**Comment by mocram** [comment] 2018-06-02 20:46
There's nothing to fix about building 1_0_2 picons. They either build with a servicelist or they don't.

I'm talking about a new system that can link a picon to a channel, completely new, not hacks on top of hacks on top of the old serviceref.

For example:

`19.2e-11739.00v-1066-28663 | md5sum` = `00247C2F2934532A5F7BB0101D76A111`
perhaps frequency just 11739v

unique, but use human readable fields from kingofsat

if no match fallback to snp

`Nick Jr.` > `nickjr | md5sum` = `913C4858C66AF34FC5575FCB46F3FECB`

**Comment by mocram** [comment] 2018-06-02 20:56
If an enigma receiver would have some sort of export feature for the required data and it could be hosted on github somewhere, that would be great, or some scraper for kingofsat, although a lamedb can be altered...

just some brain farts to think about...

**Comment by Lexzie** [comment] 2018-06-03 21:35
About a whole new system I have no ideas. I was (also) thinking about improving the existing one.
If adding 1_0_2_ for radiostations is possible, that would be great. At least for the srp-links in the snp.index because they don't work.
After thinking about improving the existing system I think there is no way to make that fault proof.
If you would add the last four digits of the namespace, you also should enable that on your receiver.
(On OpenPLi this can be found on Menu>Setup>System>Customize).
And everyone should scan **exactly** the same frequency because as you can see in my example, the sub-network in the namespace is frequency-depended.

Because I use snp-picons I did not stumble upon problems caused by this yet, so I should have more examples when this should be a problem.

By the way, looking at the srp-links in my `/picon` directory I already see the sub-network in the namespace.

**Comment by AbuBaniaz** [comment] 2018-06-03 23:10
All the major images use data provided by Lyngsat. Should you wish to proceed with the fetching of data, it would be best to use Lyngsat because the orbital positions for a few sats.

For radio srp picons to work, we need to build with a lamedb file that cobtains them. I dont know how we wll achieve this.

**Comment by mocram** [comment] 2018-06-03 23:13
Providing the build server a up2date lamedb that contains all the sats, solves the 102 problem. Dropping the 102, 101, 1016, 1019 didn't happen because we live in a perfect world and everybody is using nicely scanned channellists. Oh boy, you guys should have been here a couple of years ago :-).

sub-network does indeed get used in the actual picon filename, but it does not filter strict by it, because in the past people were receiving the exact same channels, the one user had 0000, the other something else. But, this also vanishes if the picons gets build against a lamedb. Only problem, people don't build it and I have no access to an up2date lamedb.

**Comment by mocram** [comment] 2018-06-03 23:16
srp-full & snp-full are bandaid builds. using a lamedb is a perfect match

**Closed** 2018-06-05 21:36 UTC
